services:
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    healthcheck:
      test: [ "CMD", "mysql", "-h", "127.0.0.1", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}", "-e", "SELECT 1" ]
      timeout: 20s
      retries: 10
    ports:
      - "3306:3306"

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

    volumes:
      - data_db:/var/lib/mysql

    networks:
      network_db:
        aliases:
          - mysql



  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: centribal-app
    restart: always
    
    ports:
      - "8000:8000"

    env_file:
      - .env

    volumes:
      - .:/app

    networks:
      network_db:
        aliases:
          - centribal-app

volumes:
  data_db:

networks:
  network_db:
    driver: bridge
    name: network_db
    